name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/hello-app:latest .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/hello-app:latest

      - name: Setup SSH key for manifests repo
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Clone manifests repo via SSH
        run: git clone git@github.com:JorgeAntero/Projeto-5-Manifests.git root

      - name: Update image tag in manifests
        run: |
          sed -i 's|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/hello-app:latest|' root/root/deployment.yaml

      - name: Commit and push to new branch
        run: |
          cd root
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git checkout -b update-image-latest || git checkout update-image-latest
          git add root/deployment.yaml
          git commit -m "Update image tag to latest" || echo "No changes to commit"
          git push origin update-image-latest

      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install -y gh

      - name: Create Pull Request
        run: |
          cd root
          gh pr create \
            --title "Update image tag to latest" \
            --body "Atualização automática da imagem pelo GitHub Actions." \
            --base main \
            --head update-image-latest || echo "PR já existe"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
