name: Build e Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checar código
        uses: actions/checkout@v3

      - name: Login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Buildar imagem Docker
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/hello-app:latest .

      - name: Push na imagem Docker
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/hello-app:latest

      - name: Checkout no repo manifests
        uses: actions/checkout@v3
        with:
          repository: JorgeAntero/Projeto-5-Manifests
          token: ${{ secrets.GITHUB_TOKEN }}
          path: root

      - name: Atualiza a tag de imagem no manifests
        run: |
          sed -i 's|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/hello-app:latest|' root/root/deployment.yaml

      - name: Commit e Push para o repo manifests
        run: |
          cd root/root
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          
          if git diff --quiet; then
            echo "No changes to commit."
          else
            git add deployment.yaml
            git commit -m "Update image tag to latest"
            git push origin main
          fi
