name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Definir TAG
      id: vars
      run: echo "TAG=build-$(date +%s)" >> $GITHUB_ENV

    - name: Login no DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build e Push da imagem
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/hello-app:${{ env.TAG }} .
        docker push ${{ secrets.DOCKER_USERNAME }}/hello-app:${{ env.TAG }}

    - name: Clonar repo de manifestos com SSH
      uses: actions/checkout@v3
      with:
        repository: JorgeAntero/Projeto-5-My-App-Manifests
        path: manifests
        ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
        
    - name: Atualizar imagem no manifesto
      run: |
        sed -i "s|jorgeantero/hello-app:TAG|${{ secrets.DOCKER_USERNAME }}/hello-app:${{ env.TAG }}|" manifests/deployment.yaml
        cd manifests
        git config user.name "github-actions"
        git config user.email "github-actions@users.noreply.github.com"
        git checkout -b update-image-${{ env.TAG }}
        git add deployment.yaml
        git commit -m "Atualiza imagem para tag ${{ env.TAG }}"
        git push origin update-image-${{ env.TAG }}

    - name: Criar Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ github.token }}
        path: manifests
        branch: update-image-${{ env.TAG }}
        title: "Atualiza imagem para tag ${{ env.TAG }}"
        commit-message: "Atualiza imagem para tag ${{ env.TAG }}"
